name: Advanced Downloader

on:
  workflow_dispatch:
    inputs:
      urls:
        description: "Download links (separate with space)"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y aria2 zip

      - name: Download files
        run: |
          mkdir downloads
          cd downloads

          for url in ${{ github.event.inputs.urls }}
          do
            echo "Downloading $url"

            aria2c \
            -x 16 \
            -s 16 \
            -k 1M \
            --continue=true \
            "$url"

          done

      - name: Split large files
        run: |
          cd downloads

          for file in *
          do
            size=$(stat -c%s "$file")

            if [ $size -gt 100000000 ]
            then
              echo "Splitting $file"
              split -b 95M "$file" "$file.part."
              rm "$file"
            fi
          done

      - name: Create Release
        run: |
          gh release delete download --yes || true
          git tag -d download || true
          git push origin :refs/tags/download || true

          gh release create download downloads/* \
          --title "Downloaded Files" \
          --notes "Auto download"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
